### ISSUE TITLE
Add possibility to use autocomplete (search) for application versions

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/secured-resources-diff#1]
Meta-Info | Value
-- | --
ExtProjectId | OC-01.1.8
Original Estimation | 8h
Remaining Estimation | 8h

Add possibility to select/search for the application version on UI (where/if it is possible).

**Comment by ddivin-sc** [comment]
For QA: you can check it on both repositories: nexus and artifactory
[configuration.zip](https://github.com/OpusCapita/secured-resources-diff/files/3657261/configuration.zip)

**Comment by ddivin-sc** [comment]
Merged.
